# Numpy Tutorial

In [198]:
import numpy as np
import numpy.linalg as linalg 
import time

In [5]:
## Create a table from a list or a tuple using the function

a = np.array([2,3,4])

print ('a type:',a.dtype)

b = np.array([1.2, 3.5, 5.1])

print ('a type:',b.dtype)

## The [] must be specified in the line code, otherwise the line code will be interpreted as a sequence of numbers


a type: int64
a type: float64


In [8]:
## array transforms nested sequences into multidimensional array. For example:

b = np.array([ (1.5,2,3), (4,5,6) ])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [9]:
## The data type can also be specified at creation. 
## By default, it is automatically detected. Here, we force the elements of the array to be complex numbers:

c = np.array([ [1,2], [3,4] ], dtype= complex )
c


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [25]:
# The zeros function is used to create an array containing only zeros;

zeros = np.zeros( (3,4) )

# The ones function creates a table with ones;

ones = np.ones( (2,3,4), dtype= int )

# The empty function creates a table filled with indeterminate elements (i.e with what was already in memory).

empty = np.empty( (2,3) )

print ('zeros:',zeros,
       'ones:',ones,'empty:', empty)




zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] ones: [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] empty: [[1.5 2.  3. ]
 [4.  5.  6. ]]


In [33]:
# Numpy offers two functions that make it easy to create sequences of numbers.
# Like the range function except that it returns an array instead of a list,
# arange takes as argument the starting number, the ending number and the step.

print ("arange:", np.arange( 10, 30, 5 ))

print ("array:", np.array([10, 15, 20, 25]))


arange: [10 15 20 25]
array: [10 15 20 25]


In [43]:
# When we want to create sequences of real numbers and we know the number of elements we need, the linspace function is practical. 
# linspace takes as argument the number of desired elements rather than the step.

print (np.linspace( 0, 2, 9 )) # 9 numbers from 0 to 2

x = np.linspace( 0, 2*np.pi, 100 ) # Useful for evaluating a function for given points

f = np.sin(x)

print('evaluate function for given points:', f)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
evaluate function for given points: [ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.009

In [57]:
a = np.array([[0, 1, 2, 3, 4],
                 [5, 6, 7, 8, 9]])

## Number of dimensions (rows):

print ("dimensions:", a.ndim) 
    
    
## The dimensions of the array contained in a tuple of size equal to ndarray.ndim:

print ("rows and columns:", a.shape)

## Type of elements in the table (ex. int, float, numpy.int32, numpy.int16, and numpy.float64, etc)

print("type of the elements:", a.dtype.name)

## Total number of elements in the table which is equal to the ,ultiplication of shape
## Rows X Columns

print("number of elements:", a.size)

print("type of object:", type(a))

dimensions: 2
rows and columns: (2, 5)
type of the elements: int64
number of elements: 10
type of object: <class 'numpy.ndarray'>


## Basic operations

### Arithmetique

In [66]:
## The arithmetic operators are applied element by element.
## The result is contained in a new table of the same dimension. For example:

a = np.array([20,30,40,50])
print("a=", a)

b = np.arange( 4 )
print ("b=", b)

c = a-b
print ("substraction of a - b=", c)

print('b exponent 2=',b**2)

print('transform a:',10*np.sin(a))

print('evaluate a<35=',a<35)

a= [20 30 40 50]
b= [0 1 2 3]
substraction of a - b= [20 29 38 47]
b exponent 2= [0 1 4 9]
transform a: [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
evaluate a<35= [ True  True False False]


In [68]:
## Unlike many other languages, the "product / multiplication" operator is not the dot product. 
## The product is elements by elements:

A = np.array([[1,1],
              [0,1]])

B = np.array([[2,0],
              [3,4]])

print ('product element by element:', A*B)     # product element by element

print ('matricial product:', np.dot(A,B))      # matricial product


product element by element: [[2 0]
 [0 4]]
matricial product: [[5 4]
 [3 4]]


In [81]:
## Some operators like + = and * = make changes on the spot (no new tables are created).

a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
print ('a=', a)

b += a
print('b=', b)


a= [[3 3 3]
 [3 3 3]]
b= [[3.09253913 3.7750344  3.31792014]
 [3.2776462  3.73646601 3.73783938]]


### Unitary Operators

In [87]:
a = np.random.random((2,3))
print('a =', a)

print ('sum a =', a.sum())

print ('min a =', a.min())

print ('max a =', a.max())

a = [[0.30403417 0.66061974 0.81239986]
 [0.02428742 0.20758681 0.71513213]]
sum a = 2.7240601338131993
min a = 0.02428741934037537
max a = 0.8123998588530807


In [94]:
## By default, these operators consider the arrays as a list of elements without regard to dimensions. 
## On the other hand, by specifying the parameter axis (dimension), it is possible to apply the operator only according to this dimension.

b = np.arange(12).reshape(3,4)

print ('b=', b)

print('sum of each column =', b.sum(axis=0))

print('sum of each row =', b.sum(axis=1))

print ('cumulative sum of each row = ', b.cumsum(axis=1))

b= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum of each column = [12 15 18 21]
sum of each row = [ 6 22 38]
cumulative sum of each row =  [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


## Linear Algebra Operators

In [132]:
a = np.array([[1.0, 2.0], [4.0, 3.0]])

print ("a =,", a)

print ('transpose a:', a.transpose())

print ('inverse a:', linalg.inv(a))


u = np.eye(2) # Identity Matrix 2x2; "eye" represents "I"

print ("identity matrix 2 X 2:", u)

print ("trace u =", np.trace(u))


j = np.array([[0.0, -1.0], [1.0, 0.0]])

print ('matrix j=', j)

print ('matricial product j**j=', j , '**',j ,'=', np.dot(j,j)) ## Matricial product

## Solve a linear system

y = np.array([[5.], [7.]])

print ("y = " , y)

print ("solve system a*x = y :", np.linalg.solve(a, y))

# values / eigenvectors of a matrix

print ("eigenvectors of j=", eig(j))



a =, [[1. 2.]
 [4. 3.]]
transpose a: [[1. 4.]
 [2. 3.]]
inverse a: [[-0.6  0.4]
 [ 0.8 -0.2]]
identity matrix 2 X 2: [[1. 0.]
 [0. 1.]]
trace u = 2.0
matrix j= [[ 0. -1.]
 [ 1.  0.]]
matricial product j**j= [[ 0. -1.]
 [ 1.  0.]] ** [[ 0. -1.]
 [ 1.  0.]] = [[-1.  0.]
 [ 0. -1.]]
y =  [[5.]
 [7.]]
solve system a*x = y : [[-0.2]
 [ 2.6]]
eigenvectors of j= (array([0.+1.j, 0.-1.j]), array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]]))


### Indexation, slicing and iteration

In [155]:
## One dimension

## One-dimensional arrays can be indexed, sliced, and iterated essentially as lists.

a = np.arange(10)**3

print ("a =", a)

print ("third term of a = ", a[2])

print ("slice array =", a[2:5])

## Slice from beginning to index 6 (excluded), assign one element out of two to -1000

a[:6:2] = -1000

print (a)

## Allows to reverse the order of elements of a

b = a[::-1]

print (b)

## Run a loop on each element of a 

for i in a:
      print (i ** (2))

a = [  0   1   8  27  64 125 216 343 512 729]
third term of a =  8
slice array = [ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]
1000000
1
1000000
729
1000000
15625
46656
117649
262144
531441


In [162]:
## N dimensions

b = np.array([[ 0,  1,  2,  3],
            [10, 11, 12, 13],
            [20, 21, 22, 23],
            [30, 31, 32, 33],
            [40, 41, 42, 43]])

## Extract the 4th element of the third row

print(b[2,3])

## Extract each column of the second column of b

print(b[0:5,1])

## Same as precedent example

print (b[:,1])

# Extract each column of the 2nd and 3rd row of b

print (b[1:3,:])




23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]


In [177]:
## Copy of tables
d = a.copy()       # create new table with the elements of an existing one

d

array([[2., 2., 9., 3.],
       [0., 5., 5., 3.],
       [5., 3., 8., 3.]])

In [190]:
## Modification of dimensions
## The dimensions (the shape) of an array can be modified in several ways:

a = np.floor(10*np.random.random((3,4)))

print ('a = ',a)

print(a.shape)

## Flattens the table

print("flaten a =",a.ravel())

## Transpose a

print("transpose a =",a.transpose())

## Change the shape of the table

a.shape = (6, 2)

a

a= [[7. 6. 0. 4.]
 [4. 7. 7. 2.]
 [0. 4. 4. 0.]]
(3, 4)
flaten a = [7. 6. 0. 4. 4. 7. 7. 2. 0. 4. 4. 0.]
transpose a = [[7. 4. 0.]
 [6. 7. 4.]
 [0. 7. 4.]
 [4. 2. 0.]]


array([[7., 6.],
       [0., 4.],
       [4., 7.],
       [7., 2.],
       [0., 4.],
       [4., 0.]])

In [194]:
## resize and reshape are other ways to change the dimensions of the table

## resize returns a copy of the array with the dimensions specified as argument:

b = np.resize(a,(2,6))

print (b)

## reshape returns an array pointing to the same memory space but having the specified dimensions:

c = np.reshape(a,(2,6))

print (c)


[[7. 6. 0. 4. 4. 7.]
 [7. 2. 0. 4. 4. 0.]]
[[7. 6. 0. 4. 4. 7.]
 [7. 2. 0. 4. 4. 0.]]


### Speed of numpy

In [205]:
## One of the important advantages of Numpy tables is their speed.
## Doing operations using this data structure is much more efficient than under a representation based on nested lists.

## For example, either the following script that compares the execution time of adding a matrix to itself.

a = [ [ 1 for j in range(100) ] for i in range(100) ]
current_time = time.time()
for i in range(1000):
        a_plus_a = [ [ aij + aij for aij in ai] for ai in a ] # a + a
print ("a+a with lists:",time.time()-current_time,"seconds")

# Numpy Version
a = np.array(a)
current_time = time.time()
for i in range(1000):
    a_plus_a = a+a
print ('a+a with Numpy:',time.time()-current_time,'seconds')

## The same operation with Numpy is almost 100 times faster


a+a with lists: 0.9131979942321777 seconds
a+a with Numpy: 0.011334896087646484 seconds
